apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../default
- route.yaml
images:
- name: quay.io/konveyor/crane-secret-service
  newName: quay.io/djzager/crane-secret-service
  newTag: 99f4de1
