apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: secret-service
  namespace: openshift-migration
  labels:
    app: crane
    service: secret-service
spec:
  to:
    kind: Service
    name: secret-service
  port:
    targetPort: port-8443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
